#include <stdio.h>
#include <sys/time.h>  // Needed for time()

// Function to perform modulo with large integers
long long int mod(long long int a, long long int b)
{
    return (a % b);  // Use modulo operator for large integers
}

// Global counter for random number generator
int c = 1;

// Function to compute power (num^power)
long long int Pow(int num, int power)
{
    long long int m = 1;
    for(int i = 0; i < power; i++)
    {
        m *= num;
    }
    return m;
}

// Random number generator to produce a random float between 0 and 1
float rn()
{
    // Use a large seed based on time (casting to long long int for precision)
    struct timeval tv;
    gettimeofday(&tv, NULL);
    int seed = tv.tv_usec;
    
    // Compute a large modulus (2^32)
    long long int m = Pow(2, 32);
    
    // Constant multiplier
    int a = 123;

    // Ensure counter wraps around correctly
    if(c == m - 1)
    {
        c = 0;
    }

    // Perform the modulo operation and return a float between 0 and 1
    return (float)mod((long long int)(a * seed + c++), m) / (float)m;
}

// Function to generate random float between min and max
float randf(float min, float max)
{
    // Scale the random number generated by rn() to the range [min, max]
    return min + (max - min) * rn();
}

int main() {
    // Test the random number generator
    printf("Random number: %f\n", randf(0.0, 1.0));  // Example: Random float between 0 and 1
    printf("Random number in range [5.0, 10.0]: %f\n", randf(5.0, 10.0));  // Random float between 5 and 10
    return 0;
}